Repository cloudposse/terraform-aws-ses, pull requests merged in 2024-03, with the labels that each got.

#85 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#86 Fix tests
  examples/complete/main.tf
  examples/complete/versions.tf
  main.tf
Labels: triage

#81 Add optional SPF record and custom FROM domain
  README.md
  docs/terraform.md
  examples/complete/versions.tf
  main.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: minor, needs-test
